# Workflow file adapted from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build and Publish

# Trigger this CD on push
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows running this workflow manually from the Actions tab, useful for Developers who may want
  # to view test status on the production end, prior to main branch merge.
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version

      - name: Restore Packages
        run: dotnet restore

      - name: Build and Publish Artifact
        run: dotnet publish --configuration Release --no-restore --runtime win-x64

      - name: Rename Output
        working-directory: SimpCity\bin\Release\net5.0\win-x64\publish
        run: mv SimpCity.exe SimpCity-win-x64.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SimpCity-Artifact
          path: SimpCity\bin\Release

      - name: Create Dev Release
        uses: softprops/action-gh-release@v1
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          tag_name: dev-${{ github.sha }}
          name: Release dev-${{ github.sha }}
          target_commitish: ${{ github.sha }}
          body: |
            ${{ github.sha }}
          draft: false
          prerelease: true
          files: |
            SimpCity\bin\Release\net5.0\win-x64\publish\SimpCity-win-x64.exe

      - name: Create Prod Release
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            SimpCity\bin\Release\net5.0\win-x64\publish\SimpCity-win-x64.exe
